### ISSUE TITLE
07.02.2022 

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Ulkar-Ahmad/PragmatechFrontEndProject#1]
Salam, Ülkər.🙂

Qovluq və fayl strukturuna çox fikir verin. CSS fayllarını "css" adlı qovluğa əlavə etsəniz və fayl adlarını kiçik hərflərlə yazsanız daha yaxşı olar. Yazdığınız kodları səliqəli yazmağa çalışın. Demək olar ki, ancaq "px" ölçü vahidindən istifadə etmisiniz, "rem" (bunu daha çox məsləhət görürəm) və "em" kimi ölçü vahidlərindən də istifadə etməyə çalışın. Responsivlikdə çox köməyi olacaq. Bütün teqlərə class və ya id adı verməyə çalışın. Niyəsini bilmirsinizsə araşdırın. "Uygulama-grid-spanning.html" kimi fayl adı yazmaqdansa qısaca "index.html" yaza bilərsiniz. ".DS_Store" kimi faylları ".gitignore" faylına əlavə edə bilərsiniz. Internal CSS yazmağınızı məsləhət görmürəm. Commit mesajlarına xüsusi diqqət yetirin. Məsələn, ilk hərf böyük hərflə başlamalıdır. Düzgün commit mesajı yazmaqla bağlı [bu](https://serdarkuzucu.com/2020/04/19/git-commit-mesaji-nasil-yazilmali) məqalə faydalı ola bilər.

Uğurlar sizə!✌

**Comment by Ulkar-Ahmad** [comment]
Salam Nəzrin xanım😊İstiqamət üçün çox sağolun. Bacardığım hamısını düzəltməyə çalışacam.Bəzi mövzular çox təzədir mənimçün çətinlik çəkirəm. Böyük ehtimalla bu düzələcək .Sizinlə bu mövzularla bağlı əlaqədə olacam😊
-------- Original message --------From: Nəzrin İsbəndiyarova ***@***.***> Date: 2/7/22  4:27 AM  (GMT+04:00) To: Ulkar-Ahmad/PragmatechFrontEndProject ***@***.***> Cc: Subscribed ***@***.***> Subject: [Ulkar-Ahmad/PragmatechFrontEndProject] 07.02.2022  (Issue #1) 

Salam, Ülkər.🙂

Qovluq və fayl strukturuna çox fikir verin. CSS fayllarını "css" adlı qovluğa əlavə etsəniz və fayl adlarını kiçik hərflərlə yazsanız daha yaxşı olar. Yazdığınız kodları səliqəli yazmağa çalışın. Demək olar ki, ancaq "px" ölçü vahidindən istifadə etmisiniz, "rem" (bunu daha çox məsləhət görürəm) və "em" kimi ölçü vahidlərindən də istifadə etməyə çalışın. Responsivlikdə çox köməyi olacaq. Bütün teqlərə class və ya id adı verməyə çalışın. Niyəsini bilmirsinizsə araşdırın. "Uygulama-grid-spanning.html" kimi fayl adı yazmaqdansa qısaca "index.html" yaza bilərsiniz. ".DS_Store" kimi faylları ".gitignore" faylına əlavə edə bilərsiniz. Internal CSS yazmağınızı məsləhət görmürəm. Commit mesajlarına xüsusi diqqət yetirin. Məsələn, ilk hərf böyük hərflə başlamalıdır. Düzgün commit mesajı yazmaqla bağlı bu məqalə faydalı ola bilər.

Uğurlar sizə!✌



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

<
